/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackendRouteImport } from './routes/backend'
import { Route as CloseRegisterRouteImport } from './routes/close-register'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PriceCheckRouteImport } from './routes/price-check'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as TillRouteImport } from './routes/till'
import { Route as ZReportRouteImport } from './routes/z-report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendRoute = BackendRouteImport.update({
  id: '/backend',
  path: '/backend',
  getParentRoute: () => rootRouteImport,
} as any)
const CloseRegisterRoute = CloseRegisterRouteImport.update({
  id: '/close-register',
  path: '/close-register',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceCheckRoute = PriceCheckRouteImport.update({
  id: '/price-check',
  path: '/price-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const TillRoute = TillRouteImport.update({
  id: '/till',
  path: '/till',
  getParentRoute: () => rootRouteImport,
} as any)
const ZReportRoute = ZReportRouteImport.update({
  id: '/z-report',
  path: '/z-report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backend': typeof BackendRoute
  '/close-register': typeof CloseRegisterRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/price-check': typeof PriceCheckRoute
  '/returns': typeof ReturnsRoute
  '/till': typeof TillRoute
  '/z-report': typeof ZReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backend': typeof BackendRoute
  '/close-register': typeof CloseRegisterRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/price-check': typeof PriceCheckRoute
  '/returns': typeof ReturnsRoute
  '/till': typeof TillRoute
  '/z-report': typeof ZReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backend': typeof BackendRoute
  '/close-register': typeof CloseRegisterRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/price-check': typeof PriceCheckRoute
  '/returns': typeof ReturnsRoute
  '/till': typeof TillRoute
  '/z-report': typeof ZReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backend'
    | '/close-register'
    | '/orders'
    | '/payment'
    | '/price-check'
    | '/returns'
    | '/till'
    | '/z-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backend'
    | '/close-register'
    | '/orders'
    | '/payment'
    | '/price-check'
    | '/returns'
    | '/till'
    | '/z-report'
  id:
    | '__root__'
    | '/'
    | '/backend'
    | '/close-register'
    | '/orders'
    | '/payment'
    | '/price-check'
    | '/returns'
    | '/till'
    | '/z-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackendRoute: typeof BackendRoute
  CloseRegisterRoute: typeof CloseRegisterRoute
  OrdersRoute: typeof OrdersRoute
  PaymentRoute: typeof PaymentRoute
  PriceCheckRoute: typeof PriceCheckRoute
  ReturnsRoute: typeof ReturnsRoute
  TillRoute: typeof TillRoute
  ZReportRoute: typeof ZReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend': {
      id: '/backend'
      path: '/backend'
      fullPath: '/backend'
      preLoaderRoute: typeof BackendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/close-register': {
      id: '/close-register'
      path: '/close-register'
      fullPath: '/close-register'
      preLoaderRoute: typeof CloseRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-check': {
      id: '/price-check'
      path: '/price-check'
      fullPath: '/price-check'
      preLoaderRoute: typeof PriceCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/till': {
      id: '/till'
      path: '/till'
      fullPath: '/till'
      preLoaderRoute: typeof TillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/z-report': {
      id: '/z-report'
      path: '/z-report'
      fullPath: '/z-report'
      preLoaderRoute: typeof ZReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackendRoute: BackendRoute,
  CloseRegisterRoute: CloseRegisterRoute,
  OrdersRoute: OrdersRoute,
  PaymentRoute: PaymentRoute,
  PriceCheckRoute: PriceCheckRoute,
  ReturnsRoute: ReturnsRoute,
  TillRoute: TillRoute,
  ZReportRoute: ZReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
